package cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.service;

import java.util.List;

import cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.model.Role;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AdminService.java
//  @ Date : 2019/7/1 ����һ
//  @ Author : 
//
//



/**
 * 后台管理服务层接口
 * @author Administrator
 *
 */
public interface IAdminService extends IUserService {
	/**
	 * 获取登陆用户的用户名称(员工姓名)
	 * @return 返回用户名称
	 */
	public String getUserName();
	/**
	 * 获取登陆用户的ID
	 * @return 返回用户的id数据
	 */
	public Long getUId();
	/**
	 * 获取系统全部角色信息
	 */
	public List<Role> getAllRole();
}
