package cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.service;

import cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.model.Customer;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CustomerService.java
//  @ Date : 2019/7/1 ����һ
//  @ Author : 
//
//



/**
 * 客户服务层接口
 * @author Administrator
 *
 */
public interface ICustomerService extends IAdminService {
	/**
	 * 创建客户信息
	 * @param customer 客户信息
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean createCustomer(Customer customer);
	/**
	 * 更新用户信息
	 * @param customer
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean updateCustomer(Customer customer);
	/**
	 * 删除用户信息
	 * @param customer
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean deleteCustomer(Customer customer);
	/**
	 * 获取客户信息通过id
	 * @param customer 客户信息
	 * @return 返回客户信息
	 */
	public Customer getCustomerById(Customer customer);
	/**
	 * 获取全部客户信息
	 * @return 返回结果
	 */
	public Object getAllCustomer();
	/**
	 * 通过会员卡号获取用户
	 * @param customer
	 * @return
	 */
	public Customer getCustomerByCardNo(Customer customer);
}
