package cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.service;

import cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.model.Employee;
import cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.model.EmployeeProductCategory;
import cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.model.User;
import cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.model.UserRole;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EmployeeService.java
//  @ Date : 2019/7/1 ����һ
//  @ Author : 
//
//



/**
 * 员工服务层接口
 * @author Administrator
 *
 */
public interface IEmployeeService extends IAdminService {
	/**
	 * 创建员工信息
	 * @param user 用户信息
	 * @param employee 员工信息
	 * @param role 角色信息
	 * @param category 管理货物信息
	 * @return 返回结果，true为成功，false为失败
	 */
	public Boolean createUserAndSetEmployeeRoleCategory(User user, Employee employee, UserRole role, EmployeeProductCategory category);
	/**
	 * 更新用户信息
	 * @param user 用户信息
	 * @param employee 员工信息
	 * @param role 角色信息
	 * @param category 管理货物信息
	 * @return 返回结果，true为成功，false为失败
	 */
	public Boolean updateUserAndSetEmployeeRoleCategoryByUId(User user, Employee employee, UserRole role, EmployeeProductCategory category);
	/**
	 * 获取用户信息通过ID
	 * @param user 员工信息
	 * @return 返回结果
	 */
	public Object getUserAndSetEmployeeRoleCategoryByUid(User user);
	/**
	 * 删除员工信息
	 * @param user 员工信息
	 * @return 返回结果，true为成功，false为失败
	 */
	public Boolean deleteUserAndSetEmployeeRoleCategoryByUid(User user);
	/**
	 * 获取全部员工信息
	 * @return 返回结果
	 */
	public Object getAllUserAndSetEmployeeRoleCategory();
}
