package cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.service;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IndexService.java
//  @ Date : 2019/7/1 ����һ
//  @ Author : 
//
//



/**
 * 用户首页服务层接口
 * @author Administrator
 *
 */
public interface IIndexService extends IAdminService {
	/**
	 * 获取员工数
	 * @return 员工数
	 */
	public int getEmployeeNum();
	/**
	 * 获取商品总数
	 * @return 商品总数
	 */
	public int getProductNum();
	/**
	 * 获取顾客总数
	 * @return 顾客总数
	 */
	public int getCustomerNum();
	/**
	 * 获取总金额
	 * @return 总金额
	 */
	public Long getPrices();
}
