package cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.service;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LoginService.java
//  @ Date : 2019/7/1 ����һ
//  @ Author : 
//
//

import cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.model.User;
/**
 * 用户登陆服务层接口
 * @author Administrator
 *
 */
public interface ILoginService extends IAdminService {
	
	/**
	 * 检查用户的数据，并将获取到的user信息存入session内
	 * @param user 用户类，需要设置用户名和密码
	 * @return 返回结果，true表示拥有用户，false表示没有用户
	 */
	public Boolean checkUser(User user);
}
