package cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.service;
import java.util.List;

import cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.model.ProductCategory;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ProductCategoryService.java
//  @ Date : 2019/7/1 ����һ
//  @ Author : 
//
//



/**
 * 商品类别服务层接口
 * @author Administrator
 *
 */
public interface IProductCategoryService extends IAdminService {
	/**
	 * 获取当前货物信息
	 * @return
	 */
	public ProductCategory getCategory(ProductCategory productCategory);
	/**
	 * 获取第一个类别的全部信息
	 * @return 全部一级信息
	 */
	public List< ProductCategory> getFirstCategory();
	/**
	 * 获取第二个类别的全部信息
	 * @return 全部二级信息
	 */
	public List< ProductCategory> getSecondCategory();
	/**
	 * 获取第三个类别的全部信息
	 * @return 全部三级信息
	 */
	public List< ProductCategory> getThirdCategory();
	/**
	 * 创建第一个类别信息
	 * @param productcategory 货物类别信息
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean setFirstCategory(ProductCategory productCategory);
	/**
	 * 创建第二个类别信息
	 * @param productcategory 货物类别信息
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean setSecondCategory(ProductCategory produCtcategory);
	/**
	 *创建第三个类别信息
	 * @param productcategory 货物类别信息
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean setThirdCategory(ProductCategory produCtcategory);
	/**
	 * 获取第二个货物信息通过第一个
	 * @param productcategory 货物类别信息
	 * @return 查到的第二个信息
	 */
	public List< ProductCategory> getSecondUseFirst(ProductCategory produCtcategory);
	/**
	 * 获取第三个货物信息通过第二个
	 * @param productcategory 货物类别信息
	 * @return 查到的第三个信息
	 */
	public List< ProductCategory> getThirdUseSecond(ProductCategory produCtcategory);
	/**
	 * 创建第二个信息使用第一个
	 * @param first 货物类别信息
	 * @param second 货物类别信息
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean setSecondUseFirst(ProductCategory first, ProductCategory second);
	/**
	 * 创建第三个信息使用第二个
	 * @param second 货物类别信息
	 * @param third 货物类别信息
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean setThirdUseSecond(ProductCategory second, ProductCategory third);
	/**
	 * 更新货物信息
	 * @param productcategory 货物类别信息
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean updateCategory(ProductCategory produCtcategory);
	/**
	 * 删除货物信息
	 * @param productcategory 货物类别信息
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean deleteCategory(ProductCategory produCtcategory);
}
