package cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.service;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ProductBuyService.java
//  @ Date : 2019/7/1 ����һ
//  @ Author : 
//
//

import java.util.List;

import cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.model.Buy;
import cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.model.BuyInfo;
/**
 * 商品采购服务层接口
 * @author Administrator
 *
 */
public interface IProductBuyService extends IProductService {
	/**
	 * 创建订单信息
	 * @param buy 购买订单信息
	 * @param buyinfos 购买具体信息
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean createBuyAndSetBuyInfo(Buy buy, Object buyinfos);
	/**
	 * 删除订单信息
	 * @param buy 购买订单信息
	 * @param buyinfos 购买具体信息
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean deleteBuyAndSetBuyInfo(Buy buy, Object buyinfos);
	/**
	 * 更新订单信息
	 * @param buy 购买订单信息
	 * @param buyinfos 购买具体信息
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean updateBuyAndSetBuyInfo(Buy buy, Object buyinfos);
	/**
	 * 获取订单信息通过名称
	 * @param buy 购买订单信息
	 * @return 一个或者多个订单和订单详细信息
	 */
	public Object getBuyAndSetBuyInfoByName(Buy buy);
	/**
	 * 获取订单信息通过id
	 * @param buy 购买订单信息
	 * @return 一个订单和订单详细信息
	 */
	public List<BuyInfo> getBuyAndSetBuyInfoByBid(Buy buy);
	/**
	 * 获取全部订单信息
	 * @return 全部订单信息和订单详细信息
	 */
	public Object getAllBuyAndSetBuyInfo();
	/**
	 * 
	 * @param buy 购买订单信息
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean deleteBuy(Buy buy);
	/**
	 * 创建全部订单
	 * @return
	 */
	public List<Buy> getAllBuy();
	/**
	 * 获取购买订单
	 * @param buy
	 * @return
	 */
	public Buy getBuyByBid(Buy buy);
	/**
	 * 删除单个信息
	 * @param buyInfo
	 * @return
	 */
	public boolean deleteBuyInfoByInfoId(BuyInfo buyInfo);
}
