package cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.service;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ProductService.java
//  @ Date : 2019/7/1 ����һ
//  @ Author : 
//
//

import java.util.List;

import cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.model.Product;
/**
 * 产品服务层接口
 * @author Administrator
 *
 */
public interface IProductService extends IAdminService {
	/**
	 * 获取全部产品信息
	 * @return 全部的产品信息
	 */
	public Object getAllProduct();
	/**
	 * 设置产品信息
	 * @param product 产品信息
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean setProduct(Product product);
	/**
	 * 
	 * 获取产品信息通过名称
	 * @param product 产品信息
	 * @return 一个或多个产品信息
	 */
	public List<Product> getProductByName(Product product);
	/**
	 * 获取产品信息通过id
	 * @param product 产品信息
	 * @return 一个产品信息
	 */
	public Product getProductById(Product product);
	/**
	 * 
	 * @return 全部的被警告的信息
	 */
	public List<Product> getAllAlertProduct();
	/**
	 * 获取数据通过pcid
	 * @return 返回全部相同的信息
	 */
	public List<Product> getProductByPkPcid(Product product);
	/**
	 * 删除商品
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean deleteProductByPkPcid(Product product);
	
}
