package cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.service;
import java.util.List;

import com.mysql.cj.x.protobuf.MysqlxCrud.Order;

import cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.model.SalesOrder;
import cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.model.SalesOrderInfo;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ProductSalesOrderService.java
//  @ Date : 2019/7/1 ����һ
//  @ Author : 
//
//



/**
 * 
 * 商品销售服务层接口
 * @author Administrator
 *
 */
public interface IProductSalesOrderService extends IProductService {
	/**
	 * 创建订单和订单信息
	 * @param order 销售订单
	 * @param info 订单详细信息
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean createSeleOrdeAndSetInfo(SalesOrder order, Object info);
	/**
	 * 删除订单和订单信息
	 * @param order 销售订单
	 * @param info 订单详细信息
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean deleteSeleOrdeAndSetInfo(SalesOrder order, Object info);
	/**
	 * 更新订单和订单信息
	 * @param order 销售订单
	 * @param info 订单详细信息
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean updateSeleOrdeAndSetInfo(SalesOrder order, Object info);
	/**
	 * 获取订单和订单信息通过名称
	 * @param order 销售订单
	 * @return 多个或一个订单和订单详细信息
	 */
	public Object getSeleOrdeAndSetInfoByName(SalesOrder order);
	/**
	 * 获取订单和订单信息通过id
	 * @param order 销售订单
	 * @return 一个订单和订单详细信息
	 */
	public List<SalesOrderInfo> getSeleOrdeAndSetInfoById(SalesOrder order);
	/**
	 * 获取全部订单和订单信息
	 * @return 全部订单和订单信息
	 */
	public Object getAllSeleOrdeAndSetInfo();
	/**
	 * 删除订单信息
	 * @param order 销售订单
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean deleteSeleOrder(SalesOrder order);
	/**
	 * 获取全部订单
	 * @return
	 */
	public List<SalesOrder> getAllOrders();
	/**
	 * 获取订单通过id
	 * @param salesOrder
	 * @return
	 */
	public SalesOrder getBySOid(SalesOrder salesOrder);
	/**
	 * bid找info
	 * @param salesOrder
	 * @return
	 */
	public List<SalesOrderInfo> getAllSeleOrdeAndSetInfoBySoid(SalesOrder salesOrder);
	/**
	 * 
	 * @param salesOrderInfo
	 * @return
	 */
	public boolean deleteBuyInfoByInfoId(SalesOrderInfo salesOrderInfo);
}
