package cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.service;
import java.util.List;

import cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.model.BuyInfo;
import cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.model.Refunds;
import cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.model.RefundsInfo;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ProductRefundsService.java
//  @ Date : 2019/7/1 ����һ
//  @ Author : 
//
//



/**
 * 商品退货服务层接口
 * @author Administrator
 *
 */
public interface IProductRefundsService extends IProductService {
	/**
	 * 创建退货信息
	 * @param refunds 退货订单
	 * @param info 退货详细信息
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean createRefundsAndSetInfo(Refunds refunds, Object info);
	/**
	 * 删除退货信息
	 * @param refunds 退货订单
	 * @param info 退货详细信息
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean deleteRefundsAndSetInfo(Refunds refunds, Object info);
	/**
	 * 更新退货信息
	 * @param refunds 退货订单
	 * @param info 退货详细信息
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean updateRefundsAndSetInfo(Refunds refunds, Object info);
	/**
	 * 查询退货信息通过名称
	 * @param refunds 退货订单
	 * @return 返回一个或多个退货信息和详细信息
	 */
	public Object getRefundsAndSetInfoByName(Refunds refunds);
	/**
	 * 查询退货信息通过id
	 * @param refunds 退货订单
	 * @return 返回一个退货信息和详细信息
	 */
	public List<RefundsInfo>  getRefundsAndSetInfoById(Refunds refunds);
	/**
	 * 获取全部退货信息
	 * @return 返回全部退货信息
	 */
	public Object getAllRefundsAndSetInfo();
	/**
	 *删除退货订单
	 * @param refunds 退货订单
	 * @return 返回结果 ，true表示成功，false表示失败
	 */
	public Boolean deleteRefunds(Refunds refunds);
	/**
	 * 获取全部退货信息
	 * @return
	 */
	public List<Refunds> getAllRefunds();
	/**
	 * 删除通过id
	 * @param refundsInfo
	 * @return
	 */
	public boolean deleteRefundsInfoByInfoId(RefundsInfo refundsInfo);
	/**
	 * 查id
	 * @param refunds
	 * @return
	 */
	public Refunds getRefundsByRid(Refunds refunds);
	/**
	 * 查info
	 * @param refunds
	 * @return
	 */
	public List<RefundsInfo> getBuyAndSetBuyInfoByRid(Refunds refunds);
}
