package cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.service;
import java.util.List;

import cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.model.Storehouse;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StorehouseNameService.java
//  @ Date : 2019/7/1 ����һ
//  @ Author : 
//
//



/**
 * 仓库名称层接口
 * @author Administrator
 *
 */
public interface IStorehouseNameService extends IStorehouseService {
	/**
	 * 创建仓库名称
	 * @param storehouse 仓库信息
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean setStorehouseName(Storehouse storehouse);
	/**
	 * 获取仓库名通过名称
	 * @param storehouse 仓库信息
	 * @return  返回一个或多个仓库名称信息
	 */
	public List<Storehouse> getStorehouseByName(Storehouse storehouse);
	/**
	 * 获取仓库名通过id
	 * @param storehouse 仓库信息
	 * @return 返回一个仓库名称信息
	 */
	public Storehouse getStorehouseNameById(Storehouse storehouse);
	/**
	 * 更新仓库名称
	 * @param storehouse 仓库信息
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean updateStorehouseName(Storehouse storehouse);
	/**
	 * 删除仓库名称
	 * @param storehouse 仓库信息
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean deleteStorehouseName(Storehouse storehouse);
	/**
	 * 获取全部仓库名称
	 * @return 返回全部仓库名称信息
	 */
	public List<Storehouse> getAllStorehouse();
}
