package cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.service;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StorehouseService.java
//  @ Date : 2019/7/1 ����һ
//  @ Author : 
//
//

import java.util.List;

import cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.model.OutgoingRecord;
import cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.model.OutgoingRecordInfo;
import cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.model.Storehouse;
/**
 * 
 * 仓库服务层接口
 * @author Administrator
 *
 */
public interface IStorehouseService extends IAdminService {
	/**
	 * 获取全部仓库信息
	 * @return 仓库信息
	 */
	public Object getAllOutgoingAndInfoInfoByStorehouse();
	/**
	 * 获取仓库库存信息通过名称
	 * @param storehouse 仓库信息
	 * @return 可能是多个或一个信息
	 */
	public Object getOutgoingAndInfoInfoByStorehouseByName(Storehouse storehouse);
	/**
	 * 获取仓库库存信息通过id
	 * @param storehouse 仓库信息
	 * @return 一个信息
	 */
	public Object getOutgoingAndInfoInfoByStorehouseById(Storehouse storehouse);
	/**
	 * 获取全部 的仓库库存信息
	 * @return 全部库存信息
	 */
	public Object getAllAlertOutgoingAndInfoInfoByStorehouse();
	
	/**
	 * 获取全部info表信息
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public List<OutgoingRecordInfo> getAllOutgoingRecordInfo();
	
	/**
	 * 获取全部信息
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public List<OutgoingRecord> getAllOutgoingRecord();
	/**
	 * 获取全部被警告的信息
	 * @return
	 */
	public List<Storehouse> getAllAlertInfo();
	
}
