package cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.service;
import java.util.List;

import cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.model.SupplierProduct;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SupplierServer.java
//  @ Date : 2019/7/1 ����һ
//  @ Author : 
//
//



/**
 * 
 * 供应商服务层接口
 * @author Administrator
 *
 */
public interface ISupplierService extends IAdminService {
	/**
	 * 创建供应商信息
	 * @param supplierproduct 供应商类
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean createSupplierProduct(SupplierProduct supplierproduct);
	/**
	 * 更新供应商信息
	 * @param supplierproduct 供应商类
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean updateSupplierProductById(SupplierProduct supplierproduct);
	/**
	 * 删除供应商信息
	 * @param supplierproduct 供应商类
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Boolean deleteSupplierProductById(SupplierProduct supplierproduct);
	/**
	 * 通过名称获取供应商信息
	 * @param supplierproduct 供应商类
	 * @return 返回json
	 */
	public Object getSupplierProductByName(SupplierProduct supplierproduct);
	/**
	 * 通过id获取供应商信息
	 * @param supplierproduct 供应商类
	 * @return 返回json
	 */
	public SupplierProduct getSupplierProductById(SupplierProduct supplierproduct);
	/**
	 * 获取全部供应商信息
	 * @return 返回结果，true表示成功，false表示失败
	 */
	public Object getAllSupplierProduct();
	/**
	 * 获取产品供应商通过产品id
	 * @param supplierProduct
	 * @return
	 */
	public List<SupplierProduct> getSupplierProductByPId(SupplierProduct supplierProduct);
}
