package cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.service;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : UserService.java
//  @ Date : 2019/7/1 ����һ
//  @ Author : 
//
//

import java.util.List;

import cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.model.Menu;
import cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.model.Role;
import cn.edu.ccit.JavaEEsx.zh04.sxcsglxt.model.User;
/**
 * 用户登陆相关层接口
 * @author Administrator
 *
 */
public interface IUserService {
	/**
	 * 获取用户的角色
	 * @param userId 用户的id信息
	 * @return 返回用户的角色信息
	 */
	public List<Role> getRole(Long userId);
	/**
	 * 获取用户的权限信息
	 * @param userId 用户的id
	 * @return 用户的权限信息
	 */
	public List< Menu> getPermission(Long userId);
	/**
	 * 检查用户的数据，并将获取到的user信息存入session内
	 * @param user 用户类，需要设置用户名和密码
	 * @return 返回结果，true表示拥有用户，false表示没有用户
	 */
	public Boolean checkUser(User user);
	/**
	 * 获取用户信息
	 * @param user 用户信息
	 * @return 用户结果
	 */
	public User getUser(User user);
	/**
	 * 添加用户信息
	 * @param name 用户名称
	 * @param password 用户密码
	 * @return 返回结果，true表示添加成功，false表示添加失败
	 */
	public Boolean insertUser(String name, String password);
	/**
	 * 删除用户
	 * @param userId 用户信息类
	 * @return  返回结果，true表示删除成功，false表示删除失败
	 */
	public Boolean deleteUser(Long userId);
	/**
	 * 更新用户信息
	 * @param userId 用户信息类
	 * @return 返回结果，true表示更新成功，false表示更新失败
	 */
	public Boolean updateUser(User user);

}
